# Generated by Django 4.2.25 on 2025-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True, verbose_name='ID del Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Puntos de Lealtad',
                'verbose_name_plural': 'Puntos de Lealtad',
                'db_table': 'loyalty_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
