# Generated by Django 4.2.25 on 2025-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='ID del Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('package_type', models.CharField(default='welcome_package', max_length=100, verbose_name='Tipo de paquete')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
